export const SERIALIZATION_NAME: 'NAME' = 'NAME';
export const SERIALIZATION_PROPERTY: 'PROPERTY' = 'PROPERTY';

export const SERIALIZATION: 'SERIALIZATION' = 'SERIALIZATION';
export const DESERIALIZATION: 'DESERIALIZATION' = 'DESERIALIZATION';
